# Python environment for HF to GGUF conversion using NVIDIA CUDA
FROM nvidia/cuda:12.9.1-devel-ubuntu24.04

RUN apt update
RUN apt install -y git python3 python3-pip 

WORKDIR /workspace

RUN git clone https://github.com/ggml-org/llama.cpp.git

WORKDIR /workspace/llama.cpp

RUN pip3 install --break-system-packages -r requirements.txt

RUN mkdir -p /models